### ISSUE TITLE
`biom convert` fail using this channel, but works on bioconda

### ISSUE THREAD

**Issue by colinbrislawn** [conda-forge/biom-format-feedstock#7]
Issue: This command fails with this error:

```bash
$ biom convert -i OTU_converted.txt -o OTU.biom --to-json             --process-obs-metadata sc_separated --table-type "OTU table"

Traceback (most recent call last):
  File "/people/bris469/bin/anaconda/envs/hundo_env/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/people/bris469/bin/anaconda/envs/hundo_env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/people/bris469/bin/anaconda/envs/hundo_env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/people/bris469/bin/anaconda/envs/hundo_env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/people/bris469/bin/anaconda/envs/hundo_env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/people/bris469/bin/anaconda/envs/hundo_env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/people/bris469/bin/anaconda/envs/hundo_env/lib/python3.6/site-packages/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "/people/bris469/bin/anaconda/envs/hundo_env/lib/python3.6/site-packages/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "/people/bris469/bin/anaconda/envs/hundo_env/lib/python3.6/site-packages/biom/cli/util.py", line 26, in write_biom_table
    f.write(table.to_json(biom.parse.generatedby()))
  File "/people/bris469/bin/anaconda/envs/hundo_env/lib/python3.6/site-packages/biom/table.py", line 4278, in to_json
    raise TableException("Unsupported matrix data type.")
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /people/bris469/bin/anaconda/envs/hundo_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
attrs                     19.1.0                   pypi_0    pypi
bbmap                     37.17                         1    bioconda
biom-format               2.1.6            py36h7eb728f_0    conda-forge
biopython                 1.73             py36h14c3975_0    conda-forge
blast                     2.9.0           pl526h979a64d_3    bioconda
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py36_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
click                     6.7                        py_1    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
decorator                 4.4.0                    pypi_0    pypi
docutils                  0.14                  py36_1001    conda-forge
entrez-direct             11.0                    pl526_0    bioconda
expat                     2.2.5             he1b5a44_1003    conda-forge
fasttree                  2.1.10               h14c3975_3    bioconda
future                    0.17.1                py36_1000    conda-forge
hundo                     1.3.0                    pypi_0    pypi
idna                      2.8                      pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jsonschema                3.0.1                    pypi_0    pypi
jupyter-core              4.5.0                    pypi_0    pypi
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0               10_openblas    conda-forge
libopenblas               0.3.6                h6e990d7_4    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
mafft                     7.313                         1    bioconda
nbformat                  4.4.0                    pypi_0    pypi
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.4           py36h95a1406_0    conda-forge
openblas                  0.3.6                h6e990d7_4    conda-forge
openjdk                   11.0.1            h516909a_1016    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pandas                    0.24.2           py36hb3f55d8_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.086           pl526hf484d3e_0    bioconda
perl-compress-raw-zlib    2.086           pl526h6bb024c_1    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-io-compress          2.086           pl526hf484d3e_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.50            pl526h14c3975_0    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44_01         pl526ha1d75be_1002    conda-forge
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pigz                      2.3.4                         0    conda-forge
pip                       19.1.1                   py36_0    conda-forge
plotly                    3.7.0                    pypi_0    pypi
pyrsistent                0.15.3                   pypi_0    pypi
python                    3.6.7             h357f687_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1.1            py36h516909a_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
relatively                1.0.6                    pypi_0    pypi
requests                  2.22.0                   pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
scipy                     1.3.0            py36h921218d_0    conda-forge
setuptools                41.0.1                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.28.0               hcee41ef_1    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
traitlets                 4.3.2                    pypi_0    pypi
urllib3                   1.25.3                   pypi_0    pypi
vsearch                   2.13.1               h76f5088_0    bioconda
wheel                     0.33.4                   py36_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zip                       3.0                           0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : hundo_env
    active env location : /people/bris469/bin/anaconda/envs/hundo_env
            shell level : 5
       user config file : /people/bris469/.condarc
 populated config files : /people/bris469/.condarc
          conda version : 4.7.5
    conda-build version : 3.10.9
         python version : 2.7.16.final.0
       virtual packages : 
       base environment : /people/bris469/bin/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /people/bris469/bin/anaconda/pkgs
                          /people/bris469/.conda/pkgs
       envs directories : /people/bris469/bin/anaconda/envs
                          /people/bris469/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/2.7.16 Linux/2.6.32-642.6.2.el6.x86_64 rhel/6.6 glibc/2.12
                UID:GID : 3859:100
             netrc file : None
           offline mode : False

```
</details>

----

**Plot twist: the version of this package on bioconda totally works**
```diff
$ git diff --no-index biom-no-work.txt biom-does-work.txt | grep biom
--- a/example/mothur_sop_silva/biom-no-work.txt
+++ b/example/mothur_sop_silva/biom-does-work.txt
-biom-format               2.1.6            py36h7eb728f_0    conda-forge
+biom-format               2.1.6                    py36_1    bioconda
```

I'll bump to 2.1.7 to see if that solves my problem.

See https://github.com/biocore/biom-format/issues/816

**Comment by nsoranzo** [comment]
@colinbrislawn It seems that the upstream issue has been fixed by updating the scipy dependency. Can you confirm that updating scipy to 1.3.1 in your conda environment fixes the problem?

**Comment by wasade** [comment]
Coincidentally, am just about to cut BIOM 2.1.8 including updating the recipe.

**Comment by nsoranzo** [comment]
Closing due to no reply.
